import { Task } from '@/Types/Task.type';

export const Emptytasks: Task[] = [];

export const tasksTest: Task[] = [
  {
    title: 'Comprar víveres',
    isCompleted: false,
    isImportant: true,
    createdDate: new Date(),
    dueDate: new Date(),
    tags: [
      { name: 'Hogar', color: 'green' },
      { name: 'Hogar', color: 'green' },
      { name: 'Hogar', color: 'green' },
    ],
  },
  {
    title: 'Enviar reporte semanal',
    isCompleted: false,
    isImportant: true,
    createdDate: new Date(),
    dueDate: new Date(2025, 0, 15),
    reminderDate: new Date(2025, 0, 14),
    tags: [{ name: 'Trabajo', color: 'blue' }],
  },
  {
    title: 'Llamar al dentista para cita',
    isCompleted: true,
    isImportant: false,
    createdDate: new Date(),
    dueDate: new Date(2025, 0, 15),
    reminderDate: new Date(2025, 0, 14),
    tags: [{ name: 'Salud', color: 'red' }],
  },
  {
    title:
      'Estudiar para elaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    isCompleted: false,
    isImportant: true,
    createdDate: new Date(),
    dueDate: new Date(2025, 0, 15),
    reminderDate: new Date(2025, 0, 14),
    tags: [{ name: 'Estudio', color: 'purple' }],
  },
  {
    title: 'Revisar presupuesto del mes',
    isCompleted: false,
    isImportant: false,
    createdDate: new Date(),
    dueDate: new Date(2025, 0, 15),
    reminderDate: new Date(2025, 0, 14),
    tags: [{ name: 'Finanzas', color: 'orange' }],
  },
  {
    title: 'Hacer ejercicio',
    isCompleted: true,
    isImportant: false,
    createdDate: new Date(),
    dueDate: new Date(2025, 0, 15),
    reminderDate: new Date(2025, 0, 14),
    tags: [{ name: 'Salud', color: 'red' }],
  },
  {
    title: 'Leer un capítulo de un libro',
    isCompleted: false,
    isImportant: false,
    createdDate: new Date(),
    dueDate: new Date(2025, 0, 15),
    reminderDate: new Date(2025, 0, 14),
    tags: [{ name: 'Ocio', color: 'yellow' }],
  },
  {
    title: 'Planificar vacaciones',
    isCompleted: false,
    isImportant: true,
    createdDate: new Date(),
    dueDate: new Date(2025, 0, 15),
    reminderDate: new Date(2025, 0, 14),
    tags: [
      { name: 'Hogar', color: 'green' },
      { name: 'Viajes', color: 'cyan' },
    ],
  },
  {
    title: 'Organizar escritorio',
    isCompleted: true,
    isImportant: false,
    createdDate: new Date(),
    dueDate: new Date(2025, 0, 15),
    reminderDate: new Date(2025, 0, 14),
    tags: [{ name: 'Hogar', color: 'green' }],
  },
  {
    title: 'Actualizar perfil de LinkedIn',
    isCompleted: false,
    isImportant: true,
    createdDate: new Date(),
    dueDate: new Date(2025, 0, 15),
    reminderDate: new Date(2025, 0, 14),
    tags: [{ name: 'Trabajo', color: 'blue' }],
  },
];
